# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/sdk-php
    docker:
      - image: circleci/php:7
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt-get update && sudo apt-get -y install gcc make
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "composer.json" }}
          - v1-dependencies-{{ .Branch }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies
      - run:
          name: Update composer
          command: sudo composer self-update
      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
          - vendor
          key: v1-dependencies-{{ .Branch }}-{{ checksum "composer.json" }}

      #Initialize the project and run tests
      - run:
          name: Linting
          command: make lint
      - run:
          name: Test coverage
          command: make cover

      # Special step used to persist a temporary file to be used by another job in the workflow
      - persist_to_workspace:
          root: ~/sdk-php
          paths:
            - coverage

  sonarqube:
    working_directory: ~/sdk-php
    docker:
        # Sonarqube need OpenJDK 8 to run his analysis correctly
        - image: circleci/openjdk:8
    steps:
      - checkout
      # Special step used to attach the workflow’s workspace to the current container
      # Retrieve coverage's folder for sonarqube
      - attach_workspace:
          at: ~/sdk-php

      # Sonarqube need to have node installed to run his analysis
      - run:
          name: Install node
          command: |
            sudo apt install curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
            sudo apt install nodejs
      - run:
          name: Sonar analysis
          command: make sonar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sonarqube:
          # sonarqube's job waiting for build's job before to run
          requires:
            - build
