version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7
    working_directory: ~/sdk-php
    steps:
      - checkout
      - run: sudo composer self-update

      - run: composer install -n --prefer-dist

      - run: make lint
      - run: make cover
      - run:
          when: on_fail
          command: ls -la
      - run:
          when: on_fail
          command: cd coverage && ls -la
